### ISSUE TITLE
Something wrong maybe

### ISSUE THREAD

**Issue by Computexdsg** [beneater/error-detection-videos#4]
In this segment at the code:
```
 if (bit_position == 8) {
    strncat(message, &rx_byte, 1);                   <--- here is the problem
  }
```
maybe we have a problem because i got this error code while compiling:
invalid conversion from 'volatile byte* {aka volatile unsigned char*}' to 'const char*' [-fpermissive]
So i hope you can help me!

**Comment by beneater** [comment]
That message is a warning, so it should still be compiling. Apparently I had warnings turned off which is why I didn't get the same message. You can silence the warning by explicitly casting to `const char*` like so:

```c++
  if (bit_position == 8) {
    strncat(message, (const char *)&rx_byte, 1);
  }
```

The warning suggests there might be an issue because we're passing a `volatile` into `strncat()`—the issue is if an interrupt happens while `stncat()` is doing its thing, the value of `rx_byte` could change unexpectedly. But in our case we're calling `strncat()` from within the interrupt handler so we know it can't be interrupted by another interrupt. So it should be safe to either ignore the warning or silence it like I show above.
